# Pytorch
#### A Deep learning framework

### Getting started

In [1]:
from __future__ import print_function
import torch

In [2]:
# Constructing 5x3 matrix

x = torch.empty(5, 3)
print(x)

tensor([[1.6014e+02, 7.7146e+31, 7.2085e+31],
        [1.9603e-19, 1.5202e-19, 4.8405e+30],
        [1.7058e+28, 2.1043e-19, 7.5553e+28],
        [5.2839e-11, 7.6194e+31, 2.5744e-12],
        [1.9050e+17, 1.8318e+25, 1.3667e+34]])


In [3]:
# Constructing randomly initialized matix 

x = torch.rand(5, 3)
print(x)

tensor([[0.6958, 0.4218, 0.9976],
        [0.2524, 0.8908, 0.3909],
        [0.7479, 0.2938, 0.5926],
        [0.7700, 0.7026, 0.7553],
        [0.6184, 0.1913, 0.1094]])


In [4]:
# Construct a matrix filled zeros and dtype long

x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# Construct a tensor directly from data

x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
# Create a tensor based on an existing tensor

x = x.new_ones(5, 3, dtype = torch.double) # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype = torch.float) # override dtype!
print(x) #result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.0136,  0.3633, -1.8131],
        [-1.0596,  0.7909, -0.6502],
        [-0.5894,  0.3417, -0.3478],
        [ 0.3035,  1.2529, -0.6940],
        [ 1.0896, -0.3915,  1.1359]])


In [10]:
print(x.size())

torch.Size([5, 3])


### Operations

In [11]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.2384,  1.2828, -1.3461],
        [-0.6698,  0.8202, -0.1031],
        [-0.3420,  1.0353, -0.2621],
        [ 0.5591,  1.7951, -0.3504],
        [ 2.0460,  0.1316,  1.8236]])


In [12]:
print(torch.add(x, y))

tensor([[ 0.2384,  1.2828, -1.3461],
        [-0.6698,  0.8202, -0.1031],
        [-0.3420,  1.0353, -0.2621],
        [ 0.5591,  1.7951, -0.3504],
        [ 2.0460,  0.1316,  1.8236]])


In [13]:
# addition: providing an output tensor as argument

result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

tensor([[ 0.2384,  1.2828, -1.3461],
        [-0.6698,  0.8202, -0.1031],
        [-0.3420,  1.0353, -0.2621],
        [ 0.5591,  1.7951, -0.3504],
        [ 2.0460,  0.1316,  1.8236]])


In [16]:
# addition in place
# adds x to y

y.add_(x) # any operation that mutates a tensor in place is post fixed with an _.
print(y)

tensor([[ 0.2520,  1.6461, -3.1592],
        [-1.7294,  1.6111, -0.7532],
        [-0.9314,  1.3770, -0.6099],
        [ 0.8626,  3.0481, -1.0444],
        [ 3.1356, -0.2599,  2.9595]])


In [17]:
print(x[:, 1])

tensor([ 0.3633,  0.7909,  0.3417,  1.2529, -0.3915])


In [21]:
# resizing usign tensor.view

x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [22]:
# if you have one element tensor, use .item()

x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.3787])
-0.37869325280189514


### NumPy Bridge

In [23]:
# converting a tensor to numpy array and vice cersa is a breeze
# converting torch tensor to a numpy array

a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [24]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [25]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [28]:
# Converting np array to torch tensor
# automatic conversion

import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA Tensors

In [30]:
# let us run this cell only if CUDA is availabel
# We will use "torch.device" objects to move tensors in and out of GPU

if torch.cuda.is_available():
    device = torch.device("cuda") # a CUDA device object
    y = torch.ones_like(x, device = device) # directly create a tensor on GPU
    x = x.to(device) # or just use strings ".to("cuda")"
    z = x + y
    print(z)
    print(z.to("cpu", torch.double)) # ".to" can also change dtype together!